#!/usr/bin/env python3
"""Generate Vale rules from plugins/nucleus/references/glossary.md.

Ruled 2026-09-13: "agree, both" — the reference file is the source, and the Vale
rules are generated from it. A term cannot be defined without being enforceable,
and a rule cannot exist without a row explaining it.

Only rows marked Auto: yes become rules. A refused word that collides with a
heading, a filename or ordinary English is a prose preference, checked by reading
instead. That column is measured against the corpus, not guessed -- see the
glossary's own note on `demo`, which reads like an obvious refusal and is used
correctly 52 times.

One file per kind, so each repo sets severity per kind in its own .vale.ini:

    [*.md]
    nucleus-glossary.collapses = error   # the dir name, then the file name
    nucleus-glossary.protected = error
    nucleus-glossary.prefer    = warning      # suggestion in a DevNote repo

Writes nothing unless --out is given; prints what it would write otherwise.
"""
import re, sys, os, argparse

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GLOSSARY = os.path.join(HERE, "plugins/nucleus/references/glossary.md")

# A refusal whose replacement is only meaningful with the case preserved.
CASE_SENSITIVE = {"Chicago node", "Chicago-node", "London node"}


def rows(text):
    """Every Auto-yes row of the Refused spellings table."""
    body = text.split("## Refused spellings", 1)[1].split("\n## ", 1)[0]
    for line in body.splitlines():
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 5 or cells[0] in ("Refused", "---"):
            continue
        refused, use, kind, auto = cells[0], cells[1], cells[2], cells[3]
        if "yes" not in auto.lower():
            continue
        strip = lambda s: s.strip("`*")
        yield strip(refused), strip(use), kind.lower()


def build(pairs, kind, cased):
    """One Vale substitution rule. No level: the consuming repo sets it."""
    swap = "\n".join(f"  {k!r}: {v!r}" for k, v in sorted(pairs))
    ignorecase = "false" if cased else "true"
    return f"""# GENERATED by scripts/generate-vale-rules.py — do not edit.
# Source: plugins/nucleus/references/glossary.md, "{kind.title()}" rows marked Auto: yes.
# Edit the glossary row, then regenerate.
#
# No level is set here. Each repo chooses severity in its own .vale.ini, which is
# how one glossary binds nucleus-docs at error and a DevNote repo at warning.
extends: substitution
message: "Use '%s' instead of '%s' (Nucleus glossary, {kind})."
ignorecase: {ignorecase}
swap:
{swap}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", help="a Vale style directory, e.g. styles/nucleus-glossary")
    a = ap.parse_args()

    if not os.path.exists(GLOSSARY):
        sys.exit(f"no glossary at {GLOSSARY}")
    # Grouped by kind AND by case sensitivity: one Vale file carries one
    # ignorecase flag, so mixing the two would silently make every rule in the
    # file case-sensitive. `node` -> `Node` is the case-sensitive one, and it
    # would otherwise have made `colormetric` miss `Colormetric`.
    by_kind = {}
    for refused, use, kind in rows(open(GLOSSARY).read()):
        cs = refused in CASE_SENSITIVE
        by_kind.setdefault((kind, cs), []).append((refused, use))

    if not by_kind:
        print(f"⛔️ no Auto-yes rows found in {os.path.relpath(GLOSSARY, HERE)}")
        return 2

    for (kind, cs), pairs in sorted(by_kind.items()):
        # Inside a Vale style directory the FILE NAME is the rule name, so this
        # is `collapses.yml`, not `nucleus-glossary-collapses.yml`. Getting that
        # wrong produces `nucleus-glossary.nucleus-glossary-collapses`, which no
        # .vale.ini names — and Vale then reports a clean run rather than an error.
        name = f"{kind}{'-cased' if cs else ''}.yml"
        text = build(pairs, kind, cs)
        if a.out:
            os.makedirs(a.out, exist_ok=True)
            with open(os.path.join(a.out, name), "w") as f:
                f.write(text)
            print(f"wrote {os.path.join(a.out, name)} — {len(pairs)} rule(s)")
        else:
            print(f"--- {name} ({len(pairs)} rule(s))\n{text}")

    total = sum(len(v) for v in by_kind.values())
    print(f"\n{total} rule(s) from {os.path.relpath(GLOSSARY, HERE)}"
          + ("" if a.out else "  (dry run — pass --out to write)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
